### ISSUE TITLE
FLIT Content - Blog post - Where?  Suggested date 09/09/24

### ISSUE THREAD

**Issue by DeeMcCart** [AllSkills-tech/FLIT-placeholder#14]
EPIC:  Content / FAQ/ Chatbot

As a **role** I can **capability** so that **received benefit**
As a **system designer** I want to **explain the initial scope of FLIT.ie** to achieve **some structure in my thoughts and reach my audience**  

### Assumptions or Pre-Requisites:
* FLIT.ie site exists in some form
* It is possible to add new blog posts
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must have additional blog page cross-linked to existing
- [ ] Must have 'Where - Geographic scope of FLIT' title 

### Tasks

- [ ] Task1 Create blog-8 page
- [ ] Task2 Link each of the other blogs to it
- [ ] Task3 Link the main blog page to blog-8
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
FLIT.ie - geographic scope
The geographic scope of the first version of FLIT is southern Ireland.  Yes we area aware this is a small, niche market where it may be difficult to get started.  Ireland is, an excellent test bed for new products ad services, and should provide reasonably quick feedback on the Go-To-Market strategy and whether it is workable.

Fiinancial principles are pretty much universal, regardless of location.
However, FLIT aims to guide users through SPECIFIC processes, at a reasonably detailed level, these will vary from one territory to anotehr - for example, the procedure for checling your PRSI/ social welfare contributions and establishing your state pension entitlements, is very specific; and the actions you can take to bolster your PRSI contributions thereby increasing your pension, are equally specific both in terms of knowing what office to contact, and knowing what is within your power to request under the Irish legal and financial systems.

Therefore FLIT.ie is initially an Irish solution.  Once established in Ireland, we will be eyeing up territories of interest which are likely to be UK (because of proximity and prior experience of founders) and South Africa (because of scale and growth of youth market).
