### ISSUE TITLE
FLIT Feature - site disclaimer

### ISSUE THREAD

**Issue by DeeMcCart** [AllSkills-tech/FLIT-placeholder#16]
EPIC:  DOCUMENTATION & STRUCTURE

As a **Product Owner** I want to **clearly state that this site is not giving financal advice and is for entertainment purposes only** to achieve **clear expectations at the outset for site users**  

### Assumptions or Pre-Requisites:
* This applies both to placeholder site and to final FLIT.ie site
*
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must
- [ ] Must

### Tasks

- [ ] Task1 Determine appropriate text
- [ ] Task2 Find a sensible place to put this (bottom of landing page?)
- [ ] Task3 Add it into FLIT_placeholder
- [ ] Task4 Add it into FLIT_FP Merge

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion
