### ISSUE TITLE
Approach authoritative content providers for partnerships

### ISSUE THREAD

**Issue by DeeMcCart** [AllSkills-tech/FLIT-placeholder#17]
EPIC:  CONTENT

As a **Product manager** I want to **provide content which is authoritative** to achieve **credibility and distinguish from opinion-driven processes**  
As a **user** I want to **clearly see whether content is puff or solid piece** to achieve **authoritative advice and guidance on my financial matters**  

### Assumptions or Pre-Requisites:
* There is a market gap for authoritative content created by wise, experienced advisors
* Falling into a trap of opinion-led articles is foolish and not good for FLIT long-term direction
* There are other opinion-led articles which, while useful, aren't necessarily fact-checked

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must provide fact-checking history (academic-type references)
- [ ] Show clearly the soure of information or advice

### Tasks

- [ ] Task1 Appraoch Steven Barrett re partnership / initial article
- [ ] Task2 Approach Eelevate financial (Wexford) re article
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion
