### ISSUE TITLE
FLIT Content: Prioritise Articles & Sequence of publication

### ISSUE THREAD

**Issue by DeeMcCart** [AllSkills-tech/FLIT-placeholder#18]
EPIC:  CONTENT PLANNING

As a **Product Manager** I can **plan and execute a series of content** so that **it aligns with content marketing**
As a **Product Manager** I can **plan and execute a series of content** so that **I start to gather (free) subscribers to the site and newletter**
As a **Site Owner** I can **start to accumulate free and paid users** so that **I begin  to establish product-market fit**
As a **User** I can **see articles that are relevant and interesting to me** so that **I wish to engage further with this site**

### Assumptions or Pre-Requisites:
* Working site where it is possible to draft articles in preparation for publication
* Publishing schedule - weekly/ **two-weekly** identified and commited to; with a firm schedule for 8 weeks ahead and a loose schedule for  
* Aligned with the natural flow of time (e.g. former UK residents have steps to take to secure their UK pension, prior to April 2025
* FLIT design design must allow for article 'effetcive dates' so that when an end date is reached, the article is no longer visible (changes back to 'draft' status) <- possibly an admin task to run a weekly update job
* 
### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must have initial list preferably before finalising GTM strategy
- [ ] Must

### Tasks

- [ ] Task1 List out article titles which align with market research done to date
- [ ] Task2 Prioritise these according to audience reach/ ability to execute (might be easiest to begin with low-interest articles while the site is being proven)
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
* Introduction post to explain site purpose (make financial literacy mainstream in Ireland, bring together existing resources into one reference site that can be re-visited as needed) and encourage feedback
* Pensions entitlement for former UK employees now resident in Ireland (display until 14/04/25)
* Autoenrollment - what does it mean for you (Employer perspective, Employee perspective)
* Good financial practices (Steven Barrett article from 09/09/24)
* Student grant applications (display between 01/05 and 01/11)
* Fair Deal scheme (no expiry date)
* Gender Pay Gap reporting (possibly article before year end to show what reporting stats look like for >250 employees and shoutout to 2024 where companies with >150 employees)
* Financial literacy and guardrails for women in coercive control / financial control - what is being done in the UK (where conercive financial control is now criminalised), what is being done in Ireland (action taken recently by BOI(?) to train keyworkers in domestic refuge situations
* Pensions gap - wha does this mean for women?  What actions can be taken to improve this?
* Credit union mortgages and how to access them
* Fraud and scams, what is the difference, how can you avoid the, who can you contact
* Lifestage decisions - retirement
* Lifestage decisions - parenting
* Lifestage decisions - first long-term home
* Frauds and Scams
