### ISSUE TITLE
Agile: Prioritise Features for FLIT V1

### ISSUE THREAD

**Issue by DeeMcCart** [AllSkills-tech/FLIT-placeholder#21]
EPIC:  AGILE

As a **role** I can **capability** so that **received benefit**
As a **role** I want to **action** to achieve **desired outcome**  

### Assumptions or Pre-Requisites:
* Will re-use a lot of the coding that has already been done with the CI-PP4_Financial-Planner 
* Disable or remove features which may be complicated to support
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must have sufficient features to assemble a coherent workable solution
- [ ] Each of the chosen features must have a task on the Agile board with associated development/ QA responsibilities

### Tasks

- [ ] Task1 List existing features from CI-PP5-Planner below and tick those which should be brought through to FLIT V1
- [ ] Create articles
- [ ] Use summernote content in articles
- [ ] Update from draft to published
- [ ] 
- [ ] 
- [ ] 
- [ ] **Task2 List new features which are required to administer and support FLIT V1:**

- [ ] Administration function for articles (ref jeweller) - currently backend and a pain in the ass (plus not scaleable, cannot handover backend admin to a 3rd party)
- [ ] Administration function for users (ref jeweller) - as above 
- [ ] Efffective dates for articles
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion
